/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.quintech.entities;

import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.quintech.entities.Person.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Mar 09 11:49:19 MST 2014")
public class Person_ {
    public static volatile SingularAttribute<Person,Date> birthDate;
    public static volatile SingularAttribute<Person,String> firstName;
    public static volatile SingularAttribute<Person,String> gender;
    public static volatile SingularAttribute<Person,Integer> id;
    public static volatile SingularAttribute<Person,String> lastName;
    public static volatile SetAttribute<Person,Phone> phones;
}
