/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.quintech.entities;

import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.quintech.entities.Phone.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Mar 09 11:49:19 MST 2014")
public class Phone_ {
    public static volatile SingularAttribute<Phone,Integer> id;
    public static volatile SingularAttribute<Phone,String> number;
    public static volatile SingularAttribute<Phone,Integer> personId;
    public static volatile SingularAttribute<Phone,String> type;
}
